[2024-12-22T14:56:50.424+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-22T14:56:50.554+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_top_best_sellers_books.create_books_table scheduled__2024-12-15T00:00:00+00:00 [queued]>
[2024-12-22T14:56:50.646+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_top_best_sellers_books.create_books_table scheduled__2024-12-15T00:00:00+00:00 [queued]>
[2024-12-22T14:56:50.657+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-22T14:56:50.791+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): create_books_table> on 2024-12-15 00:00:00+00:00
[2024-12-22T14:56:50.934+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=158) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-22T14:56:50.958+0000] {standard_task_runner.py:72} INFO - Started process 164 to run task
[2024-12-22T14:56:50.950+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_top_best_sellers_books', 'create_books_table', 'scheduled__2024-12-15T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag_test.py', '--cfg-path', '/tmp/tmp9tjpn0mw']
[2024-12-22T14:56:51.007+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask create_books_table
[2024-12-22T14:56:54.530+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_top_best_sellers_books.create_books_table scheduled__2024-12-15T00:00:00+00:00 [running]> on host c50092bbd7fa
[2024-12-22T14:56:55.221+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_top_best_sellers_books' AIRFLOW_CTX_TASK_ID='create_books_table' AIRFLOW_CTX_EXECUTION_DATE='2024-12-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-15T00:00:00+00:00'
[2024-12-22T14:56:55.240+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-22T14:56:55.366+0000] {sql.py:278} INFO - Executing: CREATE TABLE IF NOT EXISTS books (
    book_id SERIAL PRIMARY KEY,
    author_id BIGINT REFERENCES author_dim(author_id),
    date_id BIGINT REFERENCES date_dim(date_id),
    price NUMERIC,
    rating VARCHAR,
    title VARCHAR,
    image VARCHAR
);
[2024-12-22T14:56:55.423+0000] {base.py:84} INFO - Retrieving connection 'books_connection'
[2024-12-22T14:56:55.465+0000] {base.py:84} INFO - Retrieving connection 'books_connection'
[2024-12-22T14:56:55.491+0000] {sql.py:553} INFO - Running statement: CREATE TABLE IF NOT EXISTS books (
    book_id SERIAL PRIMARY KEY,
    author_id BIGINT REFERENCES author_dim(author_id),
    date_id BIGINT REFERENCES date_dim(date_id),
    price NUMERIC,
    rating VARCHAR,
    title VARCHAR,
    image VARCHAR
);, parameters: None
[2024-12-22T14:56:55.607+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-22T14:56:55.615+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_top_best_sellers_books, task_id=create_books_table, run_id=scheduled__2024-12-15T00:00:00+00:00, execution_date=20241215T000000, start_date=20241222T145650, end_date=20241222T145655
[2024-12-22T14:56:55.801+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-22T14:56:57.246+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-12-22T14:56:57.282+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-22T14:56:57.290+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
